# Generated by Django 5.0.1 on 2024-01-07 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Games',
            },
        ),
        migrations.CreateModel(
            name='GameSessionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Game Session Statuses',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField(blank=True, null=True)),
                ('game_duration', models.IntegerField(blank=True, null=True)),
                ('turn_duration', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgamemate.games')),
                ('status', models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='bgamemate.gamesessionstatus')),
                ('winner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bgamemate.player')),
            ],
            options={
                'verbose_name_plural': 'Game Sessions',
            },
        ),
        migrations.CreateModel(
            name='PlayerTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_duration', models.IntegerField()),
                ('turn_date', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgamemate.gamesession')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgamemate.player')),
            ],
            options={
                'verbose_name_plural': 'Player Timings',
            },
        ),
    ]
