# Generated by Django 5.0.1 on 2024-01-08 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgamemate', '0002_player_session_alter_gamesession_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='active',
            field=models.IntegerField(default=0),
        ),
    ]
