# Generated by Django 5.0.1 on 2024-01-09 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgamemate', '0003_player_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_duration', models.IntegerField()),
                ('avg_duration', models.IntegerField()),
                ('slowest_duration', models.IntegerField()),
                ('fastest_duration', models.IntegerField()),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgamemate.gamesession')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgamemate.player')),
            ],
            options={
                'verbose_name_plural': 'Game Results',
            },
        ),
    ]
